### ISSUE TITLE
Dev Tools shows [object Object] for query keys

### ISSUE THREAD

**Issue by jhanstra** [LovesWorking/react-native-react-query-devtools#15]
Hi there! Thanks so much for building this package. It is very helpful. However I've run into an issue with it when using query keys that have objects in them. This is the way react-query recommends building query keys (e.g. ['book', { userId: 'xxxx' }]), but when I use keys like that in my app, they show as ["book, [object Object]"] in the dev tools. I think there is an issue in the `displayValue` function, or wherever that query key is gotten from the QueryClient and put in state. I took a look at the code for a bit but couldn't find the exact issue and am not sure how to get the package set up locally to play around with fixing it.

As it is it makes the dev tools difficult to use when using objects as query key parameters, because they all look the same and there isn't a way to differentiate them.

<img width="439" alt="image" src="https://github.com/user-attachments/assets/0dcdc65f-8053-49ac-bb7f-bc936a9f719b">

Thanks again! Let me know if I can help with a fix.

**Comment by LovesWorking** [comment]
Here's a cleaner version of your PR comment:
I've tested this locally and found different behaviors:

Works correctly when importing the code directly
Issue occurs when using the installed package

The component in question is /_components/devtools/QueryButton.tsx, specifically this part:

`    <Text style={styles.queryKeyText}>{`${displayValue(
        query.queryKey,
        false
      )}`}</Text>`
      

![image](https://github.com/user-attachments/assets/8d7ab8a9-45bb-48fb-b83a-3bed9d2d8c39)
![image](https://github.com/user-attachments/assets/b8b028ae-927b-46f5-b00c-c3cf22270ce6)

I'll investigate this further when I have time. In the meantime, feel free to submit a PR with a fix if you understand what's going on.

**Comment by jhanstra** [comment]
@LovesWorking thanks for the quick response. It's so weird, I can't figure it out. I'm following what I believe is exactly the logic you're using in your library directly in my component, and it's consoling logging the correct values. I don't know how it could be different 🤷🏻‍♂️ If you have any ideas feel free to investigate, but otherwise I may just live with it as is and throw together my own little dev tools or something. Doesn't _seem_ to be an issue with the package but I also can't figure out what would be wrong with my set-up. Here's what I wrote:

```
  const displayValue = (value, beautify = false) => {
    const { json } = serialize(value)

    return JSON.stringify(json, null, beautify ? 2 : undefined)
  }
  const config = useConfig()
  const queryClient = config.queryClient
  const allQueries = queryClient
    .getQueryCache()
    .findAll()
    .map(q => q.queryKey)
    .map(q => displayValue(q))

  console.log('allQueries', JSON.stringify(allQueries, null, 2))
  ```
and the output:
```
 LOG  allQueries [
  "[\"recipe:authored\",{\"name\":null}]",
  "[\"user_item\",{\"name\":\"errands\"}]"
]
```

**Comment by LovesWorking** [comment]
> @LovesWorking thanks for the quick response. It's so weird, I can't figure it out. I'm following what I believe is exactly the logic you're using in your library directly in my component, and it's consoling logging the correct values. I don't know how it could be different 🤷🏻‍♂️ If you have any ideas feel free to investigate, but otherwise I may just live with it as is and throw together my own little dev tools or something. Doesn't _seem_ to be an issue with the package but I also can't figure out what would be wrong with my set-up. Here's what I wrote, which as far as I can tell is what you have:
> 
> ```
>   const displayValue = (value, beautify = false) => {
>     const { json } = serialize(value)
> 
>     return JSON.stringify(json, null, beautify ? 2 : undefined)
>   }
>   const config = useConfig()
>   const queryClient = config.queryClient
>   const allQueries = queryClient
>     .getQueryCache()
>     .findAll()
>     .map(q => q.queryKey)
>     .map(q => displayValue(q))
> 
>   console.log('allQueries', JSON.stringify(allQueries, null, 2))
> ```
> 
> and the output (which is correct, what I would expect):
> 
> ```
>  LOG  allQueries [
>   "[\"recipe:authored\",{\"name\":null}]",
>   "[\"user_item\",{\"name\":\"errands\"}]"
> ]
> ```

It must be the superjson package. I'm testing it without it.

**Comment by LovesWorking** [comment]
It should be fixed now. Update to 1.3.2 and LMK
![image](https://github.com/user-attachments/assets/4d13565c-f942-4ee4-930f-e4f0bc377928)
.

**Comment by jhanstra** [comment]
I tried adding the latest version and am getting this error: ` LOG  Caught global error: [Error: No QueryClient set, use QueryClientProvider to set one]`. Another very odd thing that doesn't make sense to me. But I've seen it before when trying to add a different package (react-scan) so it must be something weird with my package manager set-up (I'm using Bun in a monorepo). Anyway, thank you for the fix, feel free to close. Hopefully I can figure out what's going on here and get updated to the next version.
