### ISSUE TITLE
It doesn't seem to work without Expo

### ISSUE THREAD

**Issue by JameDodgers** [LovesWorking/react-native-react-query-devtools#6]
I couldn't make it work with react-native-cli, it gave me the following error:

`Unable to resolve module expo-modules-core from /node_modules/expo-clipboard/build/Clipboard.js: expo-modules-core could not be found within the project or in these directories: node_modules`

I believe at least the README should mention this

**Comment by LovesWorking** [comment]
> I couldn't make it work with react-native-cli, it gave me the following error:
> 
> `Unable to resolve module expo-modules-core from /node_modules/expo-clipboard/build/Clipboard.js: expo-modules-core could not be found within the project or in these directories: node_modules`
> 
> I believe at least the README should mention this

Can you try version 1.1.0 ? That was before I added that package. [v1.1.0](https://github.com/LovesWorking/react-native-react-query-devtools/releases/tag/v1.1.0)

**Comment by JameDodgers** [comment]
Now it's working. Thank you

**Comment by lilblondyy** [comment]
We'll work on a fix. For now this will be the workaround.
